[program:test-async]
command=php /var/www/html/bin/console messenger:consume testAsyncQueue --memory-limit=250M --time-limit=3600
numprocs=2
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/testAsyncQueue.log
stderr_logfile=/var/log/testAsyncQueue.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true