pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        valid_languages:
            - it_IT
            - en
            - de
            - fr
        fallback_languages:
            it_IT: ''
            en: 'it_IT'
            de: 'it_IT'
            fr: 'it_IT'
        required_languages:
            - it_IT
            - en
            - de
            - fr
        default_language: it_IT
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                it_IT: ''
                en: ''
                de: ''
                fr: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
